name = "clip"
version = "1.1.0"

description = "A CLI option parser for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "drewolson", repo = "clip" }

gleam = ">= 1.11.0"

[dependencies]
gleam_stdlib = ">= 0.45.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
qcheck = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.4.1 and < 2.0.0"
